version: "3.0"

services:
  control:
    hostname: main
    build:
      context: .
      dockerfile: Dockerfile.main
    command: sleep infinity
    networks:
      - vaiolabs.io
  node1:
    hostname: srv1
    build:
      context: .
      dockerfile: Dockerfile.deb
    environment:
      SSH_USERPASS: docker
    command: ["/usr/sbin/sshd", "-D"]
    networks:
      - vaiolabs.io
  node2:
    hostname: srv2
    build:
      context: .
      dockerfile: Dockerfile.rpm
    environment:
      SSH_USERPASS: docker
    command: ["/usr/sbin/sshd", "-D"]
    networks:
      - vaiolabs.io

networks:
  vaiolabs.io:
    name: vaiolabs.io