FROM rockylinux/rockylinux:8.6
EXPOSE 22
RUN dnf install -y sudo iputils ansible-core less openssh-clients openssh-server vim python39\
    && mkdir /root/.ssh
COPY node.sh /entrypoint.sh
RUN chmod 775 /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
