---
# The  minus in YAML this indicates a list item. the playbook contains a list of plays,
# with each play being a dictionary

-
  # Hosts: lists of target hosts that we'll run playbooks on
  hosts: db
  user: root

  # Vars: variables that apply to the play on all target systems
  vars:
    motd_db: 'Welcome to DB server - Deployed By Ansible '
    motd_web: 'Welcome to Web server - Deployed By Ansible '
  # Tasks: list of tasks that will be executed  within play, including pre and post tasks
  tasks:
    - name: Configure a MOTD (Message Of The Way) on DB server
      copy:
        content: "{{ motd_db }}"
        dest: /etc/motd
      when: ansible_distribution == "rockylinux"

    - name: Configure a MOTD (Message Of The Way) on Web server
      copy:
        content: "{{ motd_web }}"
        dest: /etc/motd
      when: ansible_distribution == "debian"
  # Handlers: list of handlers (notification tasks) that are executed with `notify` keyword from `tasks`
  handlers:
    - name: Configure a MOTD (Message Of The Way) on DB server
      debug:
        msg: The MOTD was changed
  # Roles: list of roles (dedicated tasks) to be imported  into the play
  
  # Note: gather_facts need to be enabled
