---

- 

  hosts: all
  tasks:
    - name: Exploring Registers
      command: hostname -s
      register: hostname_output
    - name: showing
      debug:
        msg: "{{ hostname_output.stdout }}"

...
