---

- 

  hosts: all
  tasks:
    - name: Exploring Registers
      command: hostname -s
      when: 
        - ansible_distribution == "Rocky" 
        - ansible_distribution_major_version  | int >= 8
