---

- 

  hosts: all
  tasks:
    - name: Exploring Registers
      command: hostname -s
      when: 
        - ansible_distribution == "Rocky" 
        - ansible_distribution_major_version  | int >= 8
      register: command_register

    - name: Show registered value
      debug:
        var: command_register

