---

-
  hosts: web
  vars:
    - server: web
    - purpose: provide system calls over the http protocol
    - port: 80
  tasks:
  - name: Template a file to /tmp/config.ini
    template:
      src: config.j2
      dest: /tmp/config.ini
