---
- 
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    nginx_version: 1.18.0-6.1+deb11u3
    nginx_custom_directory: /home/docker/nginx
    web_server_port: 80

  tasks:
    - name: Update and upgrade apt
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: yes

    - name: "Install Nginx to version {{ nginx_version }}"
      apt:
        name: "nginx={{ nginx_version }}"
        state: present

    - name: Copy the Nginx configuration file to the host
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default

    - name: Create link to the new config to enable it
      file:
        dest: /etc/nginx/sites-enabled/default
        src: /etc/nginx/sites-available/default
        state: link

    - name: Create Nginx directory
      ansible.builtin.file:
        path: "{{ nginx_custom_directory }}"
        state: directory


    - name: Copy index.html to the Nginx directory
      copy:
        content: "Welcome to ansible provisioned nginx web server"
        dest: "{{ nginx_custom_directory }}/index.html"
    - name: Restart the Nginx service
      service:
        name: nginx
        state: restarted